nasdq_100 = ['VIX', 'AAPL', 'MSFT', 'GOOG', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'FB', 'COST', 'ASML', 'AVGO', 'PEP',
             'NTES', 'CSCO', 'CMCSA', 'AZN',
             'ADBE', 'INTC', 'TMUS', 'TXN', 'QCOM', 'AMD', 'AMGN', 'INTU', 'HON', 'PYPL', 'CHTR', 'ISRG', 'AMAT',
             'NFLX', 'ABNB', 'ADP',
             'SBUX', 'BKNG', 'MDLZ', 'ADI', 'JD', 'MU', 'GILD', 'REGN', 'CSX', 'VRTX', 'TEAM', 'LRCX', 'FISV', 'MAR',
             'PANW', 'ATVI', 'MRNA',
             'WDAY', 'FTNT', 'MELI', 'ILMN', 'KDP', 'MRVL', 'KHC', 'KLAC', 'AEP', 'CRWD', 'PAYX', 'ORLY', 'LULU', 'EXC',
             'DXCM', 'NXPI', 'SNPS',
             'PDD', 'CTSH', 'MNST', 'ADSK', 'CDNS', 'IDXX', 'CTAS', 'BIDU', 'DDOG', 'XEL', 'WBA', 'DLTR', 'MCHP',
             'ROST', 'EA', 'VRSK', 'LCID',
             'ALGN', 'FAST', 'BIIB', 'EBAY', 'ODFL', 'ZS', 'ZM', 'PCAR', 'CPRT', 'SGEN', 'ANSS', 'SIRI', 'MTCH', 'VRSN',
             'OKTA', 'SPLK', 'CEG', 'SWKS', 'DOCU', ]
