# TODO: Build a class over this data, so it will provide exchange, coin..
exchance_symbol_pairs = [
    ('binance', 'ACA/USDT'),
    ('binance', 'ETH/USDT'),
    ('binance', 'SAND/USDT'),
    ('binance', 'DOT/USDT'),
    ('binance', 'SOL/USDT'),
    ('binance', 'ADA/USDT'),
    ('binance', 'AXS/USDT'),
    ('binance', 'BTC/USDT'),
    ('binance', 'KSM/USDT'),
    ('binance', 'XRP/USDT'),
    ('binance', 'MANA/USDT'),
    ('binance', 'XLM/USDT'),
    ('binance', 'EGLD/USDT'),
    ('binance', 'FLUX/USDT'),
    ('binance', 'CRV/USDT'),
    ('binance', 'APE/USDT'),
    ('binance', 'ROSE/USDT'),
    # ('binance', 'LUNA/USDT'),
    ('binance', 'OGN/USDT'),
    ('binance', 'RNDR/USDT'),
    ('binance', 'GLMR/USDT'),
    ('binance', 'BNB/USDT'),
    ('binance', 'SHIB/USDT'),
    ('binance', 'CAKE/USDT'),
    ('binance', 'FTM/USDT'),
    ('binance', 'RUNE/USDT'),
    ('binance', 'KDA/USDT'),
    ('binance', 'MATIC/USDT'),
    ('binance', 'MOVR/USDT'),
    ('binance', 'GALA/USDT'),
    ('kucoin', 'QRDO/USDT'),
    ('kucoin', 'HTR/USDT'),
    ('kucoin', 'RMRK/USDT'),
    ('kucoin', 'SOUL/USDT'),
    ('kucoin', 'LYXE/USDT'),
    ('kucoin', 'TEL/USDT'),
    ('kucoin', 'VRA/USDT'),
    ('mexc_global', 'GCOIN/USDT')
]

DB_PATH = 'ccxt_1m.db'
